services:
  - type: web
    name: smagritrade-backend
    env: node
    buildCommand: npm install
    startCommand: node src/index.js
    envVars:
      - key: MONGODB_URI
        fromDatabase:
          name: smagritrade-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: EMAIL_SERVICE
        value: gmail
      - key: EMAIL_USER
        value: your_email@gmail.com
      - key: EMAIL_PASS
        value: your_email_password